#!/bin/bash

pull_from_host()
{
	echo "pull"
        read -p 'Host to pull from? ' HOST
	PULLPATH=${HOST}:.ssh/id_rsa*
        scp $PULLPATH ~/.ssh/
}

if [ ! -f ~/.ssh/id_rsa ]; then
	echo "no keys on this host, select an option"
	select yn in "Pull from another host" "Generate" "Abort"; do
		case $yn in
			"Pull from another host" ) pull_from_host; break;;
			"Generate" ) ssh-keygen -t rsa -q; break;;
			"Abort" ) exit;;
		esac
	done
fi
if [ -f ~/.ssh/id_rsa ]; then
	echo "pushing authorization"
	cat ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys | ssh "$1" 'cat - ~/.ssh/authorized_keys | sort -u > ~/.ssh/authorized_keys'
	LCS=`cat ~/.ssh/id_rsa.pub | md5sum`
	RCS=`ssh "$1" 'if [ -f ~/.ssh/id_rsa.pub ]; then cat ~/.ssh/id_rsa.pub | md5sum; fi'`
	if [ "X$LCS" != "X$RCS" ]; then
		echo "pushing keys"
		ssh "$1" 'if [ -f ~/.ssh/id_rsa ]; then mv ~/.ssh/id_rsa ~/.ssh/id_rsa_old; mv ~/.ssh/id_rsa.pub ~/.ssh/id_rsa.pub_old; fi'
		scp ~/.ssh/id_rsa* "$1":.ssh/
	else
		echo "keys match"
	fi
else
	echo 'no keys, aborting'
fi

